.github/workflows/main.yml
name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Hello
        run: echo "Hello GitHub Action Working!"

